name: build

on:
    pull_request:
    push:
        branches:
            - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ 3.7, 3.9 ]
        include:
          - os: ubuntu-latest
            python-version: 3.8
            openmp: "True"
          - os: ubuntu-latest
            python-version: 3.8
            openmp: "False"
            deploy_pypi_source : "True"
          - os: macos-latest
            python-version: 3.8
            openmp: "False"
    env:
      RUNNER_OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
      COVERAGE: "False"
      DEPLOY_PYPI_SOURCE: "${{ matrix.deploy_pypi_source == 'True' && 'True' || 'False' }}"
      USE_OPENMP: "${{ matrix.openmp == 'True' && 'True' || 'False' }}"
      PYPI_SERVER: ${{ secrets.PYPI_SERVER }}
      PYPI_USER: ${{ secrets.PYPI_USER }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      PYPI_API_ENDPOINT: ${{ secrets.PYPI_API_ENDPOINT }}

    steps:
      - name: install
        run: |
          if [ "$RUNNER_OS" = "macOS" ]; then CC=gcc ; fi
          if [ "$RUNNER_OS" = "macOS" ]; then CXX=g++; fi
          source continuous_integration/Travis/install_dependencies.sh
      - name: test
        run: |
          flake8 .
          bash continuous_integration/Travis/test_script.sh
      - name: coverage
        run: if [[ "$COVERAGE" == "True" ]]; then coveralls; fi
      - name: deploy
        run: bash continuous_integration/Travis/deploy_script.sh
