name: build

on:
    pull_request:
    push:
        branches:
            - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ 3.7, 3.9 ]
        include:
          - os: ubuntu-latest
            python-version: 3.8
            openmp: "True"
          - os: ubuntu-latest
            python-version: 3.8
            openmp: "False"
            deploy_pypi_source : "True"
          - os: macos-latest
            python-version: 3.8
            openmp: "False"
    env:
      RUNNER_OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
      COVERAGE: "False"
      DEPLOY_PYPI_SOURCE: "${{ matrix.deploy_pypi_source == 'True' && 'True' || 'False' }}"
      USE_OPENMP: "${{ matrix.openmp == 'True' && 'True' || 'False' }}"

    steps:
      - name: Echo envs
        run: echo $RUNNER_OS $PYTHON_VERSION $COVERAGE $USE_OPENMP $DEPLOY_PYPI_SOURCE